def github(name, version, options = nil)
  options ||= {}
  options[:repo] ||= "boxen/puppet-#{name}"
  mod name, version, :github_tarball => options[:repo]
end

github "boxen",    "2.1.0"
github "homebrew", "1.1.2"
github "stdlib",   "4.1.0", :repo => "puppetlabs/puppetlabs-stdlib"
github "concat",   "1.0.0", :repo => "puppetlabs/puppetlabs-concat"
